### ISSUE TITLE
Add Jenkins

### ISSUE THREAD

**Issue by ruanbekker** [ruanbekker/awesome-docker-compose#46]
```
version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - 8080:tcp
      - 50000:tcp
    environment:
      JENKINS_OPTS: ''
    volumes:
      - ':/var/jenkins_home'
```
