### ISSUE TITLE
Add PrivateBin

### ISSUE THREAD

**Issue by ruanbekker** [ruanbekker/awesome-docker-compose#52]
```
version: '3.8'
services:
  privatebin:
    image: privatebin/nginx-fpm-alpine:latest
    ports:
      - 8080:8080:tcp
    environment:
      PUID: ''
      PGID: ''
    volumes:
      - /portainer/Files/AppData/PrivateBin:/srv/data
      - /portainer/Files/AppData/Config/PrivateBin:/srv/cfg
```
